[env:weact_stm32h562vgt6]
platform = https://github.com/platformio/platform-ststm32.git
board = weact_stm32h562vgt6 ; // Используем наш кастомный JSON профиль
framework = stm32cube

platform_packages = 
    framework-stm32cubeh5 @ https://github.com/samspencer5991/framework-stm32cubeh5.git

board_build.ldscript = src/linker/32CORE.ld 

build_flags =
    -I src/drivers/Inc
    -I src/configs
    -I src/libraries/STM32FreeRTOS/src

build_src_filter =
    +<*>
    +<libraries/STM32FreeRTOS/src/*.c>
    +<libraries/STM32FreeRTOS/src/*.cpp>
    +<drivers/*.c>
    +<drivers/*.cpp>