[env:weact_stm32h562vgt6]
platform = ststm32
board = genericSTM32H562VG
framework = stm32cube

; 1. Путь к линковщику (относительно корня проекта)
board_build.ldscript = src/linker/32CORE.ld // Путь к скрипту линковщика

; 2. Пути к инклюдам (.h)
build_flags = 
    -I src/drivers/Inc                       // Заголовочные файлы драйверов
    -I src/configs                           // stm32h5xx_hal_conf.h и FreeRTOSConfig.h
    -I src/libraries/STM32FreeRTOS/src       // Заголовочные файлы FreeRTOS

; 3. Фильтрация исходных файлов (.c/.cpp) от папки src/
build_src_filter = 
    +<*>                                      // Включить всё в src/
    +<libraries/STM32FreeRTOS/src/*.c>        // Исходники FreeRTOS (.c)
    +<libraries/STM32FreeRTOS/src/*.cpp>      // Исходники FreeRTOS (.cpp)
    +<drivers/*.c>                            // Исходники драйверов (.c)
    +<drivers/*.cpp>                          // Исходники драйверов (.cpp)