[env:weact_stm32h562vgt6]
platform = ststm32
board = genericSTM32H562VG
framework = stm32cube

; 1. Путь к линковщику (linker script .ld)
board_build.ldscript = src/linker/32CORE.ld ; Укажите путь к .ld файлу

; 2. Пути к пользовательским библиотекам (замена lib_dir)
lib_extra_dirs = 
    src/libraries ; Путь к папке с библиотеками

; 3. Пути к драйверам и папкам с заголовочными файлами (.h)
build_flags = 
    -I src/drivers/Inc ; Путь к инклюдам драйверов
    -I src/configs ; Путь к конфигурационным файлам (например, FreeRTOSConfig.h, stm32h5xx_hal_conf.h)
    -I src/libraries/STM32FreeRTOS/src

; 4. Подключение исходных файлов драйверов (.c/.cpp), если они лежат вне src/
build_src_filter = 
    +<*>
    +<libraries/STM32FreeRTOS/src/*.c>
    +<libraries/STM32FreeRTOS/src/*.cpp>
    +<drivers/*.c>
    +<drivers/*.cpp>
;    +<../path/to/your/drivers/src/*.c> ; Добавление .c файлов драйверов в сборку